# Generated by Django 5.0.7 on 2026-08-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('expert', 'Эксперт'), ('admin', 'Администратор')], default='client', max_length=10, verbose_name='Роль'),
        ),
    ]
