# Generated by Django 5.0.7 on 2026-08-31 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0002_alter_propertyobject_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('meeting_requested', 'Запрошена встреча'), ('meeting_scheduled', 'Встреча назначена'), ('deal_confirmed', 'Сделка подтверждена'), ('in_progress', 'В процессе оформления'), ('completed', 'Успешно завершено')], default='draft', max_length=30, verbose_name='Статус')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Предварительная цена')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Итоговая цена')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер договора')),
                ('current_step', models.IntegerField(default=1, verbose_name='Текущий шаг выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_expert', models.ForeignKey(blank=True, limit_choices_to={'role': 'expert'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='Назначенный инженер')),
                ('property_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='objects.propertyobject', verbose_name='Объект недвижимости')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ / Сделка',
                'verbose_name_plural': 'Заказы / Сделки',
                'ordering': ['-created_at'],
            },
        ),
    ]
