# Generated by Django 5.0.7 on 2026-08-31 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Дата встречи')),
                ('time_slot', models.CharField(choices=[('9-13', 'С 9:00 до 13:00'), ('13-18', 'С 13:00 до 18:00')], max_length=10, verbose_name='Временной интервал')),
                ('address', models.TextField(verbose_name='Адрес встречи')),
                ('status', models.CharField(choices=[('scheduled', 'Запланирована'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='scheduled', max_length=20, verbose_name='Статус встречи')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки / Комментарии')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Встреча / Осмотр инженера',
                'verbose_name_plural': 'Встречи / Осмотры инженеров',
                'ordering': ['scheduled_date', 'time_slot'],
            },
        ),
    ]
