# Generated by Django 5.0.7 on 2026-09-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_propertyobject_id_and_more'),
        ('orders', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='property_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='objects.propertyobject', verbose_name='Объект недвижимости'),
        ),
    ]
