# Generated by Django 5.0.7 on 2026-09-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_property_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_step',
            field=models.IntegerField(default=7, verbose_name='Запрошенный клиентом этап'),
        ),
    ]
