# Generated by Django 5.0.7 on 2026-08-31 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name': 'Шаг', 'verbose_name_plural': 'Шаги'},
        ),
        migrations.RemoveField(
            model_name='step',
            name='description',
        ),
        migrations.RemoveField(
            model_name='step',
            name='number',
        ),
        migrations.RemoveField(
            model_name='step',
            name='order',
        ),
        migrations.AddField(
            model_name='step',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AddField(
            model_name='step',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='step',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название шага'),
        ),
    ]
