# Generated by Django 5.0.7 on 2026-07-27 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('house', 'дом'), ('apartment', 'квартира'), ('comercial', 'комерческая недвижимость'), ('LAND', 'земельный участок')], max_length=50, verbose_name='Тип объекта')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь (м2)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
