# Generated by Django 5.0.7 on 2026-08-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyobject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='propertyobject',
            name='property_type',
            field=models.CharField(choices=[('house', 'дом'), ('apartment', 'квартира'), ('commercial', 'комерческая недвижимость'), ('LAND', 'земельный участок')], max_length=50, verbose_name='Тип объекта'),
        ),
    ]
