# Generated by Django 5.0.7 on 2026-09-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_alter_propertyobject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyobject',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='propertyobject',
            name='property_type',
            field=models.CharField(choices=[('house', 'Дом'), ('apartment', 'Квартира'), ('commercial', 'Коммерческая недвижимость'), ('LAND', 'Земельный участок')], max_length=50, verbose_name='Тип объекта'),
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('saved', 'Сохранено'), ('approved', 'Утверждено')], default='draft', max_length=20, verbose_name='Статус')),
                ('object_name', models.CharField(max_length=255, verbose_name='Наименование объекта')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Заказчик')),
                ('designer_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Проектировщик')),
                ('location', models.TextField(verbose_name='Местоположение объекта')),
                ('design_basis', models.TextField(verbose_name='Основание для проектирования')),
                ('purpose', models.TextField(verbose_name='Назначение объекта')),
                ('construction_type', models.CharField(choices=[('new', 'Новое строительство'), ('reconstruction', 'Реконструкция'), ('extension', 'Пристройка'), ('renovation', 'Реконструкция / переустройство')], max_length=30, verbose_name='Вид строительных работ')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая площадь (м²)')),
                ('building_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Площадь застройки (м²)')),
                ('floors', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество этажей')),
                ('rooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество помещений')),
                ('design_stage', models.CharField(choices=[('one_stage', 'Одностадийное проектирование'), ('two_stage', 'Двухстадийное проектирование')], default='one_stage', max_length=20, verbose_name='Стадия проектирования')),
                ('alternative_design', models.BooleanField(default=False, verbose_name='Необходимость разработки альтернативного варианта')),
                ('architectural_requirements', models.TextField(blank=True, default='', verbose_name='Архитектурно-планировочные требования')),
                ('structural_requirements', models.TextField(blank=True, default='', verbose_name='Конструктивные решения')),
                ('engineering_requirements', models.TextField(blank=True, default='', verbose_name='Инженерное обеспечение')),
                ('landscaping_requirements', models.TextField(blank=True, default='', verbose_name='Благоустройство территории')),
                ('safety_requirements', models.TextField(blank=True, default='', verbose_name='Требования по безопасности')),
                ('customer_requirements', models.TextField(blank=True, default='', verbose_name='Особые требования заказчика')),
                ('special_conditions', models.TextField(blank=True, default='', verbose_name='Особые условия строительства')),
                ('design_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала проектирования')),
                ('design_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания проектирования')),
                ('customer_signature', models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись заказчика')),
                ('designer_signature', models.CharField(blank=True, default='', max_length=255, verbose_name='Подпись исполнителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('property_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignment', to='objects.propertyobject', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Задание на проектирование',
                'verbose_name_plural': 'Задания на проектирование',
                'ordering': ['-created_at'],
            },
        ),
    ]
